CREATE DATABASE IF NOT EXISTS LOJA;
USE LOJA;

CREATE TABLE CLIENTE(
ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
TELEFONE VARCHAR(22) NOT NULL,
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_CLIENTE),
ID_ORDEM INT NOT NULL,
FOREIGN KEY (ID_ORDEM) REFERENCES SERVICO(ID_ORDEM)
);

CREATE TABLE VEICULO(
ID_VEICULO INT AUTO_INCREMENT NOT NULL,
PLACA VARCHAR(9) NOT NULL,
ANO VARCHAR(4),
MODELO VARCHAR(100),
VALOR NUMERIC(10,2 ) NOT NULL,
PRIMARY KEY(ID_VEICULO),
ID_CLIENTE INT NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL, 
EMAIL VARCHAR(150) NOT  NULL,
SENHA VARCHAR(8) NOT NULL, 
PRIMARY KEY(ID_USUARIO),
ID_ORDEM INT NOT NULL, 
FOREIGN KEY (ID_ORDEM) REFERENCES SERVICO(ID_ORDEM)
);

CREATE TABLE SERVICO(
ID_ORDEM INT AUTO_INCREMENT NOT NULL,
DATA_EXPEDICAO DATE NOT NULL,
DESCRICAO VARCHAR(300) NOT NULL,
SOLUCAO VARCHAR(300) NOT NULL,
PRIMARY KEY(ID_ORDEM),
ID_CLIENTE INT NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
ID_VEICULO INT NOT NULL,
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO),
ID_USUARIO INT NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

ALTER TABLE CLIENTE ADD COLUMN ID_ORDEM INT NOT NULL,
ADD CONSTRAINT FK_CLIENTE_SERVICO
FOREIGN KEY (ID_ORDEM) REFERENCES SERVICO(ID_ORDEM);