CREATE DATABASE IF NOT EXISTS LOJA;
USE LOJA;

-- 1. Criação das tabelas base (sem dependências circulares imediatas)
CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
    TELEFONE VARCHAR(22) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ID_ORDEM INT,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE VEICULO (
    ID_VEICULO INT AUTO_INCREMENT NOT NULL,
    PLACA VARCHAR(9) NOT NULL,
    ANO VARCHAR(4),
    MODELO VARCHAR(100),
    VALOR NUMERIC(10,2) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    PRIMARY KEY (ID_VEICULO),
    CONSTRAINT FK_VEICULO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    SENHA VARCHAR(8) NOT NULL,
    ID_ORDEM INT,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE SERVICO (
    ID_ORDEM INT AUTO_INCREMENT NOT NULL,
    DATA_EXPEDICAO DATE NOT NULL,
    DESCRICAO VARCHAR(300) NOT NULL,
    SOLUCAO VARCHAR(300) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_VEICULO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_ORDEM),
    CONSTRAINT FK_SERVICO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_SERVICO_VEICULO FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO),
    CONSTRAINT FK_SERVICO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- 2. Adição das chaves estrangeiras restantes após a criação de todas as tabelas
ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_SERVICO 
FOREIGN KEY (ID_ORDEM) REFERENCES SERVICO(ID_ORDEM);

ALTER TABLE USUARIO 
ADD CONSTRAINT FK_USUARIO_SERVICO 
FOREIGN KEY (ID_ORDEM) REFERENCES SERVICO(ID_ORDEM);