CREATE DATABASE SPEAK;
USE SPEAK;

CREATE TABLE CANDIDATOS(
ID_CANDI SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(30) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PONTUACAO INT NOT NULL,
NIVEL_RESULTADO VARCHAR(50),
CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE CANDIDATOS
RENAME COLUMN ID TO ID_CANDI;

CREATE TABLE USUARIOS(
ID_USU INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(255) NOT NULL,
PERFIL VARCHAR(100) NOT NULL DEFAULT 'ASSISTENTE'
);

INSERT INTO CANDIDATOS (NOME, TELEFONE, EMAIL, PONTUACAO, NIVEL_RESULTADO) 
VALUES 
('Carlos Eduardo Oliveira', '(11) 98765-4321','carlos.eduardo@email.com', 2, 'A1 - Iniciante'),
('Mariana Rocha Santos', '(11) 97654-3210', 'mariana.rocha@email.com',5, 'B1 - Intermediário'),
('Lucas Gabriel Mendes', '(11) 96543-2109','lucas.mendes@email.com', 9, 'C1 - Avançado');

INSERT INTO USUARIOS (NOME, EMAIL, SENHA, PERFIL) 
VALUES 
('Laura Cristina Silva Souza', 'gerencia@speakup.com.br', 1234, 'GERENTE'),
('Ana Paula Ribeiro', 'secretaria@speakup.com.br', 1234, 'GERENTE'),
('Carlos Eduardo Oliveira', 'carlos.eduardo@email.com', 1234, 'ASSISTENTE');